



ALTER TABLE tickets
ADD COLUMN "can_replace_ticket" BOOLEAN;





-- Add tokens columns to user table
ALTER TABLE users
    ADD COLUMN daily_replace_tokens INT DEFAULT 2,
    ADD COLUMN monthly_delete_tokens INT DEFAULT 1;

-- Create tags table
CREATE TABLE tags (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

-- Create junction table for ticket-tag relationship
CREATE TABLE ticket_tags (
    ticket_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    PRIMARY KEY (ticket_id, tag_id),
    FOREIGN KEY (ticket_id) REFERENCES tickets(id),
    FOREIGN KEY (tag_id) REFERENCES tags(id)
);





ALTER TABLE tickets
    ALTER COLUMN replacement_ticket_request_date DROP NOT NULL;




INSERT INTO tags (name) VALUES
                            ('Development'),
                            ('Design'),
                            ('Testing'),
                            ('Documentation'),
                            ('Research'),
                            ('Project Management'),
                            ('Maintenance'),
                            ('Customer Support'),
                            ('Deployment'),
                            ('Training');










